Repository eab-agency/wilmington-nextjs, pull requests merged in 2025-07, with the labels that each got.

#426 Feature/new modal plugin integration
  .gitignore
  possibleTypes.json
  scripts/switch-env.sh
  src/lib/wordpress/fetchRedirects.js
Labels: Review effort 3/5, Possible security concern

#428 Feature new alert messages
  src/components/HomepageModal.module.css
Labels: Review effort 2/5

#430 Refactor custom settings and modal visibility logic
  possibleTypes.json
  scripts/check-block-types.js
  scripts/check-graphql-schemas.js
  scripts/check-wordpress-env.js
  src/components/HomepageModal.tsx
  src/functions/contextProviders/CustomSettingsProvider.tsx
  src/lib/wordpress/_query-partials/customSettingsAndLatestAlertsFields.js
Labels: Review effort 2/5

#434 Bugfix eventdates fix2
  src/styles/layouts/newsAndEvents/_eventsArticle.scss
  wp-templates/single-event.js
Labels: Review effort 2/5

#436 Qa
  package.json
  src/styles/layouts/newsAndEvents/_eventsArticle.scss
  yarn.lock
Labels: Review effort 1/5

#438 Fix optional chaining for studentOrganizations in SingleProgram compo…
  wp-templates/single-program.js
Labels: Review effort 1/5
